monolog:
    handlers:
        # Handler par défaut en DEV et TEST
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]

        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]

when@prod:
    monolog:
        handlers:
            main:
                action_level: info
                handler: nested

            nested:
                type: stream
                path: "%kernel.logs_dir%/prod.log"
                level: info

            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
