monolog:
    handlers:
        filter_for_errors:
            action_level: error
            handler: error_log_handler

        error_log_handler:
            type: error_log
            level: info