monolog:
    handlers:
        # Handler par défaut en DEV et TEST
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]

        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]

when@prod:
    monolog:
        handlers:
            # En PROD, on remplace main par un "fingers_crossed"
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405] # on ignore les erreurs 404/405 dans les logs

            nested:
                type: stream
                path: "%kernel.logs_dir%/prod.log"
                level: debug

            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
