security:
    password_hashers:
        App\Entity\User: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
            logout: true

        light:
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
            logout: true

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }