-- Initial schema for Loup de classe
CREATE TABLE user (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(180) NOT NULL UNIQUE,
  roles JSON NOT NULL,
  password VARCHAR(255) NOT NULL,
  name VARCHAR(100) DEFAULT NULL
) DEFAULT CHARSET=utf8mb4;

CREATE TABLE child (
  id INT AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(100) NOT NULL,
  parent_id INT DEFAULT NULL,
  CONSTRAINT FK_child_parent FOREIGN KEY (parent_id) REFERENCES user(id) ON DELETE SET NULL
) DEFAULT CHARSET=utf8mb4;

CREATE TABLE slot (
  id INT AUTO_INCREMENT PRIMARY KEY,
  label VARCHAR(255) NOT NULL,
  start_at DATETIME NOT NULL,
  end_at DATETIME NOT NULL,
  active TINYINT(1) DEFAULT 1
) DEFAULT CHARSET=utf8mb4;

CREATE TABLE reservation (
  id INT AUTO_INCREMENT PRIMARY KEY,
  slot_id INT NOT NULL,
  user_id INT NOT NULL,
  child_id INT DEFAULT NULL,
  justification TEXT DEFAULT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'pending',
  created_at DATETIME DEFAULT NULL,
  CONSTRAINT FK_res_slot FOREIGN KEY (slot_id) REFERENCES slot(id) ON DELETE CASCADE,
  CONSTRAINT FK_res_user FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE,
  CONSTRAINT FK_res_child FOREIGN KEY (child_id) REFERENCES child(id) ON DELETE SET NULL
) DEFAULT CHARSET=utf8mb4;
